name: Prime Performance
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4431132373865694
title: Priming your potential for greatness in your book
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fddfc5'
    - '#1e0000'
    - '#79868f'
    - '#8bbefd'
    - '#24495c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.48552267951890826
purpose: []
