name: Prime Performance
favicon: null
layout_spectrum: 0.50423
typography_spectrum: 0.4431132373865694
title: Priming your potential for greatness in your book
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b2937'
    - '#455972'
    - '#190003'
    - '#85755c'
    - '#8a9a75'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
